---
url: https://podman.io
theme: jekyll-theme-dinky

plugins:
  - jemoji
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-avatar
  - jekyll-mentions
  - jekyll-sitemap

description: "Podman is a daemonless container engine for developing, managing, and running OCI Containers on your Linux System. Containers can either be run as root or in rootless mode."

readme_index:
  enabled: true
  remove_originals: false

excerpt_separator: "<!--readmore-->"

feed:
  categories:
    - blogs
    - new
    - releases
    - talks

authors:
  sumantro:
    name: Sumantro
    display_name: sumantrom
    gravatar:
    email: sumantro@redhat.com
    web: 
    twitter: BytesOfBinary
    github: sumantro93
  adrianr:
    name: Adrian Reber
    display_name: Adrian Reber
    email: areber@redhat.com
    github: adrianreber
    twitter: adrian__reber
  afbjorklund:
    name: Anders F Björklund
    display_name: Anders Björklund
    email: anders.f.bjorklund@gmail.com
    github: afbjorklund
  baude:
    name: Brent Baude
    display_name: Brent Baude
    email: bbaude@redhat.com
    web: https://people.redhat.com/baude/
    twitter: bbaude
    github: baude
  balage:
    name: Balázs Németh
    display_name: Balázs Németh
    email: jobbara.artalmatlan@gmail.com
    web: https://balagetech.com
    twitter:
    github: abalage
  cevich:
    name: Chris Evich
    display_name: Chris Evich
    email: cevich@redhat.com
    github: cevich
  daniel-wtd:
    name: Daniel Schier
    display_name: Daniel Schier
    email: daniel@while-true-do.io
    web: https://while-true-do.io
    twitter: daniel_wtd
    github: daniel-wtd
  dwalsh:
    name: Dan Walsh
    display_name: Dan Walsh
    gravatar: 75d88487c07b14b6c7aa0599fce600bf
    email: dwalsh@redhat.com
    web: https://people.redhat.com/dwalsh/
    twitter: rhatdan
    github: rhatdan
  ehaynes:
    name: Ed Haynes
    display_name: Ed Haynes
    gravatar: 
    email: ehaynes@redhat.com
    web: https://redhat.com
    twitter: 
    github: edhaynes
  emacchi:
    name: Emilien Macchi
    display_name: Emilien Macchi
    gravatar:
    email:
    web: https://redhat.com
    twitter: EmilienMacchi
    github: EmilienM
  haraldh:
    name: Harald Hoyer
    display_name: Harald Hoyer
    gravatar: 3de14a8eee27f8bc4c58acf5409827df
    email: harald@redhat.com
    web: https://harald.hoyer.xyz
    twitter: haraldhoyer
    github: haraldh
  ipbabble:
    name: William Henry
    display_name: ipbabble
    gravatar:
    email: whenry@redhat.com
    web: https://redhat.com
    twitter: ipbabble
    github: ipbabble
  jwhonce:
    name: Jhon Honce
    display_name: Jhon Honce
    gravatar:
    email: jhonce@redhat.com
    web: https://redhat.com
    twitter: jwhonce
    github: jwhonce
  kshirinkin:
    name: Kirill Shirinkin
    display_name: Kirill Shirinkin
    email: kirill@mkdev.me
    web: https://mkdev.me/en
    twitter: Fodoj
    github: Fodoj
  lsm5:
    name: Lokesh Mandvekar
    display_name: Lokesh Mandvekar
    gravatar:
    email: lsm5@fedoraproject.org
    web: https://redhat.com
    twitter:
    github: lsm5
  mheon:
    name: Matthew Heon
    display_name: Matt Heon
    gravatar:
    email: mheon@redhat.com
    web: https://redhat.com
    twitter:
    github: mheon
  pvanroy:
    name: Parker Van Roy
    display_name: Parker Van Roy
    gravatar:
    email: pvanroy@redhat.com
    web: https://redhat.com
    github: ParkerVR
  tristanC:
    name: Tristan de Cacqueray
    display_name: tristanC
    gravatar:
    email: tdecacqu@redhat.com
    twitter:
    gitub: TristanCacqueray
  tsweeney:
    name: Tom Sweeney
    display_name: Tom Sweeney
    gravatar: c69c8419c8e4d1bbedc7874281453781
    email: tsweeney@redhat.com
    web: https://redhat.com
    twitter: TSweeneyRedHat
    github: TomSweeneyRedhat
  vrothberg:
    name: Valentin Rothberg
    display_name: Valentin Rothberg
    email: rothberg@redhat.com
    github: vrothberg
    twitter: vlntnrthbrg
  bhepworth:
    name: Bryan Hepworth
    display_name: Bryan Hepworth
    email: bryan.hepworth@newcastle.ac.uk
    github: BryanHepworth
    twitter: bryan_hepworth
  ahyder:
    name: Austin Hyder
    display_name: Austin Hyder
    email: ahyder@redhat.com
    web: https://redhat.com
    github: amhyder
  fhsinchy:
    name: Farhan Hasin Chowdhury
    display_name: Farhan Hasin Chowdhury
    gravatar:
    email: mail@farhan.info
    web: https://www.farhan.info
    twitter: frhnhsin
    github: fhsinchy

  afrocoder:
    name: Leon N
    display_name: Leon N
    gravatar:
    email: me@leonnunes.dev
    web: https://leonnunes.dev
    twitter: frustratedpepe
    github: afro-coder
