url: https:/podman.io
theme: jekyll-theme-dinky

plugins:
  - jemoji
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-avatar
  - jekyll-mentions
  - jekyll-sitemap

readme_index:
  enabled: true
  remove_originals: false

excerpt_separator: "<!--readmore-->"

authors:
  baude:
    name: Brent Baude
    display_name: Brent Baude
    email: bbaude@redhat.com
    web: https://people.redhat.com/baude/
    twitter: bbaude
    github: baude
  dwalsh:
    name: Dan Walsh
    display_name: Dan Walsh
    gravatar: 75d88487c07b14b6c7aa0599fce600bf
    email: dwalsh@redhat.com
    web: https://people.redhat.com/dwalsh/
    twitter: rhatdan
    github: rhatdan
  emacchi:
    name: Emilien Macchi
    display_name: Emilien Macchi
    gravatar:
    email:
    web: https://redhat.com
    twitter: EmilienMacchi
    github: EmilienM
  ipbabble:
    name: William Henry
    display_name: ipbabble
    gravatar:
    email: whenry@redhat.com
    web: https://redhat.com
    twitter: ipbabble
    github: ipbabble
  jwhonce:
    name: Jhon Honce
    display_name: Jhon Honce
    gravatar:
    email: jhonce@redhat.com
    web: https://redhat.com
    twitter: jwhonce
    github: jwhonce
  mheon:
    name: Matthew Heon
    display_name: Matt Heon
    gravatar:
    email: mheon@redhat.com
    web: https://redhat.com
    twitter:
    github: mheon
  tristanC:
    name: Tristan de Cacqueray
    display_name: tristanC
    gravatar:
    email: tdecacqu@redhat.com
    twitter:
    gitub: TristanCacqueray
  tsweeney:
    name: Tom Sweeney
    display_name: Tom Sweeney
    gravatar: c69c8419c8e4d1bbedc7874281453781
    email: tsweeney@redhat.com
    web: https://redhat.com
    twitter: TSweeneyRedHat
    github: TomSweeneyRedhat
  haraldh:
    name: Harald Hoyer
    display_name: Harald Hoyer
    gravatar: 3de14a8eee27f8bc4c58acf5409827df
    email: harald@redhat.com
    web: https://harald.hoyer.xyz
    twitter: haraldhoyer
    github: haraldh
